### ISSUE TITLE
Player: adicionar atualizacao de email e senha

### ISSUE THREAD

**Issue by grun00** [grun00/Fatec-IES300---Back#15]
Precisamos da rota para mutar email e senha do player

**Comment by trgarcia** [comment]
Acho que seria interessante uma rota que já pode mudar todas os dados do player. @grun00  o que vc acha? 

Se não quiser alterar tudo, é só enviar só os que quer alterar.

**Comment by grun00** [comment]
Isso, eh basicamente um Update. Pode ser todos os dados ou só os que vão mudar

**Comment by trgarcia** [comment]
Verifiquei que essa funcionalidade já estava funcionando kk. 
Apenas coloquei as informações do endpoint no README.
